# Import The Data

In [24]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Read csv file

In [4]:
df=pd.read_csv("C:\\Users\\revat\\Downloads\\House Price Prediction.csv")
df

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

#Export the data set

In [5]:
df.drop('date', axis= 1, inplace=True)


In [6]:
column_to_move = 'price'
new_position = 20
column=df[column_to_move]
df = df.drop(column_to_move, axis=1)
df = pd.concat([df.iloc[:, :new_position], column, df.iloc[:, new_position:]], axis=1)
df

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      7129300520         3       1.00         1180      5650     1.0   
1      6414100192         3       2.25         2570      7242     2.0   
2      5631500400         2       1.00          770     10000     1.0   
3      2487200875         4       3.00         1960      5000     1.0   
4      1954400510         3       2.00         1680      8080     1.0   
...           ...       ...        ...          ...       ...     ...   
21608   263000018         3       2.50         1530      1131     3.0   
21609  6600060120         4       2.50         2310      5813     2.0   
21610  1523300141         2       0.75         1020      1350     2.0   
21611   291310100         3       2.50         1600      2388     2.0   
21612  1523300157         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21608           0     0          3      8        1530              0   
21609           0     0          3      8        2310              0   
21610           0     0          3      7        1020              0   
21611           0     0          3      8        1600              0   
21612           0     0          3      7        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
1          1951          1991    98125  47.7210 -122.319           1690   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
...         ...           ...      ...      ...      ...            ...   
21608      2009             0    98103  47.6993 -122.346           1530   
21609      2014             0    98146  47.5107 -122.362           1830   
21610      2009             0    98144  47.5944 -122.299           1020   
21611      2004             0    98027  47.5345 -122.069           1410   
21612      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15     price  
0            5650  221900.0  
1            7639  538000.0  
2            8062  180000.0  
3            5000  604000.0  
4            7503  510000.0  
...           ...       ...  
21608        1509  360000.0  
21609        7200  400000.0  
21610        2007  402101.0  
21611        1287  400000.0  
21612        1357  325000.0  

[21613 rows x 20 columns]

In [7]:
df.columns

Index(['id', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'price'],
      dtype='object')

In [8]:
df.shape

(21613, 20)

In [9]:
df.describe()

id      bedrooms     bathrooms   sqft_living      sqft_lot  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  2.161300e+04   
mean   4.580302e+09      3.370842      2.114757   2079.899736  1.510697e+04   
std    2.876566e+09      0.930062      0.770163    918.440897  4.142051e+04   
min    1.000102e+06      0.000000      0.000000    290.000000  5.200000e+02   
25%    2.123049e+09      3.000000      1.750000   1427.000000  5.040000e+03   
50%    3.904930e+09      3.000000      2.250000   1910.000000  7.618000e+03   
75%    7.308900e+09      4.000000      2.500000   2550.000000  1.068800e+04   
max    9.900000e+09     33.000000      8.000000  13540.000000  1.651359e+06   

             floors    waterfront          view     condition         grade  \
count  21613.000000  21613.000000  21613.000000  21613.000000  21613.000000   
mean       1.494309      0.007542      0.234303      3.409430      7.656873   
std        0.539989      0.086517      0.766318      0.650743      1.175459   
min        1.000000      0.000000      0.000000      1.000000      1.000000   
25%        1.000000      0.000000      0.000000      3.000000      7.000000   
50%        1.500000      0.000000      0.000000      3.000000      7.000000   
75%        2.000000      0.000000      0.000000      4.000000      8.000000   
max        3.500000      1.000000      4.000000      5.000000     13.000000   

         sqft_above  sqft_basement      yr_built  yr_renovated       zipcode  \
count  21613.000000   21613.000000  21613.000000  21613.000000  21613.000000   
mean    1788.390691     291.509045   1971.005136     84.402258  98077.939805   
std      828.090978     442.575043     29.373411    401.679240     53.505026   
min      290.000000       0.000000   1900.000000      0.000000  98001.000000   
25%     1190.000000       0.000000   1951.000000      0.000000  98033.000000   
50%     1560.000000       0.000000   1975.000000      0.000000  98065.000000   
75%     2210.000000     560.000000   1997.000000      0.000000  98118.000000   
max     9410.000000    4820.000000   2015.000000   2015.000000  98199.000000   

                lat          long  sqft_living15     sqft_lot15         price  
count  21613.000000  21613.000000   21613.000000   21613.000000  2.161300e+04  
mean      47.560053   -122.213896    1986.552492   12768.455652  5.401822e+05  
std        0.138564      0.140828     685.391304   27304.179631  3.673622e+05  
min       47.155900   -122.519000     399.000000     651.000000  7.500000e+04  
25%       47.471000   -122.328000    1490.000000    5100.000000  3.219500e+05  
50%       47.571800   -122.230000    1840.000000    7620.000000  4.500000e+05  
75%       47.678000   -122.125000    2360.000000   10083.000000  6.450000e+05  
max       47.777600   -121.315000    6210.000000  871200.000000  7.700000e+06

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   bedrooms       21613 non-null  int64  
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64  
 4   sqft_lot       21613 non-null  int64  
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  int64  
 7   view           21613 non-null  int64  
 8   condition      21613 non-null  int64  
 9   grade          21613 non-null  int64  
 10  sqft_above     21613 non-null  int64  
 11  sqft_basement  21613 non-null  int64  
 12  yr_built       21613 non-null  int64  
 13  yr_renovated   21613 non-null  int64  
 14  zipcode        21613 non-null  int64  
 15  lat            21613 non-null  float64
 16  long           21613 non-null  float64
 17  sqft_living15  21613 non-null  int64  
 18  sqft_l

In [11]:
x=df.iloc[:, :-1].values
y=df.iloc[:, -1].values

In [12]:
print(x)

[[ 7.12930052e+09  3.00000000e+00  1.00000000e+00 ... -1.22257000e+02
   1.34000000e+03  5.65000000e+03]
 [ 6.41410019e+09  3.00000000e+00  2.25000000e+00 ... -1.22319000e+02
   1.69000000e+03  7.63900000e+03]
 [ 5.63150040e+09  2.00000000e+00  1.00000000e+00 ... -1.22233000e+02
   2.72000000e+03  8.06200000e+03]
 ...
 [ 1.52330014e+09  2.00000000e+00  7.50000000e-01 ... -1.22299000e+02
   1.02000000e+03  2.00700000e+03]
 [ 2.91310100e+08  3.00000000e+00  2.50000000e+00 ... -1.22069000e+02
   1.41000000e+03  1.28700000e+03]
 [ 1.52330016e+09  2.00000000e+00  7.50000000e-01 ... -1.22299000e+02
   1.02000000e+03  1.35700000e+03]]


In [13]:
print(y)

[221900. 538000. 180000. ... 402101. 400000. 325000.]


In [15]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state=101)

#Training and Testing data set

In [16]:
x_train

array([[ 4.01950016e+09,  4.00000000e+00,  2.50000000e+00, ...,
        -1.22265000e+02,  2.07000000e+03,  4.61000000e+03],
       [ 6.07323023e+09,  3.00000000e+00,  2.25000000e+00, ...,
        -1.22184000e+02,  1.80000000e+03,  8.14000000e+03],
       [ 6.02150084e+09,  5.00000000e+00,  3.00000000e+00, ...,
        -1.22386000e+02,  1.37000000e+03,  4.60600000e+03],
       ...,
       [ 1.54580210e+09,  3.00000000e+00,  2.25000000e+00, ...,
        -1.22051000e+02,  1.51000000e+03,  7.62500000e+03],
       [ 2.97980075e+09,  2.00000000e+00,  1.00000000e+00, ...,
        -1.22317000e+02,  1.46300000e+03,  4.32000000e+03],
       [ 4.36520062e+09,  3.00000000e+00,  1.00000000e+00, ...,
        -1.22371000e+02,  1.04000000e+03,  7.74000000e+03]])

In [17]:
x_test

array([[ 2.13170124e+09,  2.00000000e+00,  1.00000000e+00, ...,
        -1.21981000e+02,  1.60000000e+03,  9.61600000e+03],
       [ 2.17500135e+08,  4.00000000e+00,  2.25000000e+00, ...,
        -1.22335000e+02,  1.89000000e+03,  8.58000000e+03],
       [ 7.13330038e+09,  4.00000000e+00,  2.50000000e+00, ...,
        -1.22311000e+02,  1.48000000e+03,  4.30000000e+03],
       ...,
       [ 5.12621028e+09,  3.00000000e+00,  2.50000000e+00, ...,
        -1.21986000e+02,  2.71000000e+03,  1.12820000e+05],
       [ 7.29960187e+09,  3.00000000e+00,  2.50000000e+00, ...,
        -1.22198000e+02,  1.60800000e+03,  5.17500000e+03],
       [ 2.34680027e+09,  3.00000000e+00,  3.00000000e+00, ...,
        -1.22395000e+02,  2.27000000e+03,  1.81800000e+04]])

In [18]:
y_train

array([493000., 425000., 588000., ..., 272450., 552000., 394000.])

In [19]:
y_test

array([349950., 450000., 635000., ..., 560000., 299000., 555000.])

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [27]:
from sklearn.ensemble import RandomForestRegressor 
regressor= RandomForestRegressor (n_estimators = 100, random_state= 0) 
regressor.fit(x_train, y_train)

RandomForestRegressor(random_state=0)

In [31]:
y_pred= regressor.predict(x_test)
np.set_printoptions (precision=2) 
print (np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[214975.1 349950. ]
 [214975.1 450000. ]
 [219845.1 635000. ]
 ...
 [219845.1 560000. ]
 [219845.1 299000. ]
 [225692.6 555000. ]]


In [34]:
Mean_absolute_error = mean_absolute_error (y_test,y_pred) 
print('Mean absolute_error:',Mean_absolute_error)

Mean_squared_error = mean_squared_error(y_test,y_pred)
print('Mean squared error:',Mean_squared_error)

R_squared = r2_score (y_test,y_pred) 
print('R_squared:',R_squared)


Mean absolute_error: 323095.15765358997
Mean squared error: 235213646811.42618
R_squared: -0.6568206537989765
